export const data = {
  centre_cards_num: 3,
  waking_werewolves: ["Werewolf", "Alpha Wolf", "Mystic Wolf", "Giant Wolf"],
  werewolves: [
    "Werewolf",
    "Alpha Wolf",
    "Mystic Wolf",
    "Dream Wolf",
    "Giant Wolf",
  ],
  centre_werewolf_card_choices: ["Werewolf"],
  immediate_doppleganger_roles: [
    "Alpha Wolf",
    "Mystic Wolf",
    "Seer",
    "Apprentice Seer",
    "Paranormal Investigator",
    "Robber",
    "Witch",
    "Troublemaker",
    "Drunk",
  ],
  adjacent_doppelganger_roles: ["Revealer", "Gremlin"],
  insomniac_relevant_roles: [
    "Alpha Wolf",
    "Robber",
    "Witch",
    "Troublemaker",
    "Gremlin",
  ],
  beholden_roles: ["Seer", "Apprentice Seer"],
  giant_roles: ["Giant Wolf"],
  roles: [
    {
      name: "Copycat",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "vampire",
    },
    {
      name: "Doppelgänger",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
    },
    {
      name: "Werewolf",
      villager_team: false,
      werewolf_team: true,
      tanner_team: false,
      max_num: 2,
      default_num: 2,
    },
    {
      name: "Giant Wolf",
      villager_team: false,
      werewolf_team: true,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "custom",
      hidden: true,
    },
    {
      name: "Alpha Wolf",
      villager_team: false,
      werewolf_team: true,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Mystic Wolf",
      villager_team: false,
      werewolf_team: true,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Minion",
      villager_team: false,
      werewolf_team: true,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
    },
    {
      name: "Apprentice Tanner",
      villager_team: false,
      werewolf_team: false,
      tanner_team: true,
      max_num: 1,
      default_num: 0,
      expansion: "bonus-pack",
    },
    {
      name: "Mason",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 2,
      default_num: 0,
    },
    {
      name: "Seer",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 1,
    },
    {
      name: "Apprentice Seer",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Paranormal Investigator",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Robber",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 1,
    },
    {
      name: "Witch",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Troublemaker",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 1,
    },
    {
      name: "Aura Seer",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "bonus-pack",
    },
    {
      name: "Gremlin",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "vampire",
    },
    {
      name: "Drunk",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
    },
    {
      name: "Insomniac",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
    },
    {
      name: "Squire",
      villager_team: false,
      werewolf_team: true,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "bonus-pack",
    },
    {
      name: "Beholder",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "bonus-pack",
    },
    {
      name: "Revealer",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Dream Wolf",
      villager_team: false,
      werewolf_team: true,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Villager",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 3,
      default_num: 1,
    },
    {
      name: "Tanner",
      villager_team: false,
      werewolf_team: false,
      tanner_team: true,
      max_num: 1,
      default_num: 0,
    },
    {
      name: "Hunter",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
    },
    {
      name: "Bodyguard",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "daybreak",
    },
    {
      name: "Prince",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "bonus-pack",
    },
    {
      name: "Cursed",
      villager_team: true,
      werewolf_team: false,
      tanner_team: false,
      max_num: 1,
      default_num: 0,
      expansion: "bonus-pack",
    },
  ],
};
